"""change get_or_create -if instance

Revision ID: 55ce5cd84764
Revises: 16b403a9c5fa
Create Date: 2024-12-12 13:56:06.018713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ce5cd84764'
down_revision: Union[str, None] = '16b403a9c5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
