"""get_or_create -staticmethod +classmethod

Revision ID: 600cd96ed71b
Revises: 1a77a75c7eff
Create Date: 2024-12-12 12:51:30.201532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600cd96ed71b'
down_revision: Union[str, None] = '1a77a75c7eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
